library(dplyr)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")

name <- unique(SCC[,4])
name <- as.character(name)
g <- grep("Coal$",name)
name <- name[g]
m <- merge(NEI,SCC)
m <- select(m,c(fips,SCC,type,Emissions,year,EI.Sector))
m <- filter(m, EI.Sector %in% name)
m <- arrange(m,year)
total <- sapply(split(m$Emissions,m$year),sum)
png("plot4.png")
with(m,plot(unique(year),total,pch=19, ylim = c(310000,620000), xlab = "Years", ylab = "PM2.5 Emission (tons)", main = "Emissions from Coal combustion-related sources"))
model <- lm(total~unique(year),m)
abline(model,lwd=2)
text(2002,370000,"DECREASE in Emissions")
dev.off()