library(dplyr)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")

NEI1 <- subset(NEI, fips == "24510" | fips == "06037")
name <- unique(SCC[,4])
name <- as.character(name)
g <- grep("Vehicles$",name)
name <- name[g]
m <- merge(NEI1,SCC)
m <- select(m,c(fips,SCC,type,Emissions,year,EI.Sector))
m <- filter(m, EI.Sector %in% name)
m <- arrange(m,fips,year)
m1 <- subset(m, fips == "06037")
total1 <- sapply(split(m1$Emissions,m1$year),sum)
m2 <- subset(m, fips == "24510")
total2 <- sapply(split(m2$Emissions,m2$year),sum)
png("plot6.png")
par(mfrow=c(1,2))
with(m1, plot(unique(year),total1, xlab = "years", ylab="Emission from motor vehicles s(tons)", main = "Los Angeles", pch=19))
model1 <- lm(total1~unique(year),m1)
abline(model1,lwd=3,col="red")
with(m2, plot(unique(year),total2, xlab = "years", ylab="Emission from motor vehicles (tons)", main = "Baltimore",pch=19))
model2 <- lm(total2~unique(year),m2)
abline(model2,lwd=3,col="blue")
text(2004,325,"Greater change in PM2.5")
text(2004,312,"Emissions occurs here")
dev.off()