library(dplyr)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")

NEI1 <- subset(NEI, fips == "24510")
name <- unique(SCC[,4])
name <- as.character(name)
g <- grep("Vehicles$",name)
name <- name[g]
m <- merge(NEI1,SCC)
m <- select(m,c(fips,SCC,type,Emissions,year,EI.Sector))
m <- filter(m, EI.Sector %in% name)
m <- arrange(m,year)
total <- sapply(split(m$Emissions,m$year),sum)
png("plot5.png")
with(m,plot(unique(year),total,pch=19, xlab = "Years", ylab = "PM2.5 Emission (tons)", main = "Emissions from Motor Vehicle sources in Baltimore city"))
model <- lm(total~unique(year),m)
abline(model,lwd=2)
text(2004,330,"Drastic DROP from 346 to 88 over years")
dev.off()